<?php

// For the tier labeling, you can use several options in your definitions:
// 	'item_code' => 3 // option 1 - just use tier value
// 	'item_code' => [3 => 3] // option 2 - use socket count with tier value
// 	'item_code' => ['(SOCK=3 ETH)' => 3] // option 3 - use conditions with tier value
// The system will automatically detect how you did it and act appropriately.

return [

	// Convert item types to loot filter codes (for runeword descriptions).
	'codemap' => [
		'shld' => '(SHIELD OR DIN)',
		'club' => '(CLUB)',
		'hamm' => '(HAMMER)',
		'mace' => '(MACE)',
		'h2h' => '(SIN)',
		'mele' => '(WEAPON !THROWING !BOW !XBOW !WAND)',
		'scep' => '(SCEPTER)',
		'swor' => '(SWORD)',
		'staf' => '(STAFF)',
		'tors' => '(CHEST)',
		'helm' => '(HELM OR CIRC OR BAR OR DRU)',
		'miss' => '(BOW OR XBOW)',
		'weap' => '(WEAPON)',
		'axe' => '(AXE)',
		'wand' => '(WAND)',
		'pole' => '(POLEARM)',
		'spea' => '(SPEAR)',
		'sorc' => '(ob1 OR ob2 OR ob3 OR ob4 OR ob5)',
		'h2h2' => '(SIN)',
		'pala' => '(DIN)',
		'2hsw' => '(2H SWORD)',
	],

	// Define any FILTLVL codes to apply for each tier.
	'filters' => [
		'1' => null,
		'2' => null,
		'3' => null,
		'4' => null,
		'5' => null,
		'6' => 'FILTLVL<3',
	],

	// Define your tiers and their colors.
	'colors' => [
		'1' => '%ORANGE%',
		'2' => '%PURPLE%',
		'3' => '%RED%',
		'4' => '%GOLD%',
		'5' => '%SAGE%',
		'6' => '%LIGHT_GRAY%',
	],

	// Rename items that are labeled oddly in the game files.
	'rename' => [
		'Bound by Duty' => 'Chains of Honor',
		'Widowmaker' => 'Grief',
		'Rimeraven' => 'Ravenclaw',
		'Veil Of Steel' => 'Nightwing\'s Veil',
		'Tal Rasha\'s Howling Wind' => 'Tal Rasha\'s Guardianship',
		'Cutthroat1' => 'Bartuc\'s Cut Throat',
		'Ironward' => 'Astreon\'s Iron Ward',
		'The Reedeemer' => 'Heaven\'s Light',
		'Azurewrath' => 'Lightsabre',
	],

	// Define conditions to match catch-all base items.
	'catchall' => [
		'(CIRC OR DRU OR BAR) (SOCK=2)' => 6,
		'(CIRC OR DRU OR BAR) (SOCK=3)' => 5,
		'ELT ETH CHEST' => 3,
		'EXC ETH CHEST' => 5,
		'NORM ETH CHEST' => 6,
		'ELT ZON (TABSK0>2 OR TABSK2>2)' => 4,
		'EXC ZON (TABSK0>1 OR TABSK2>1)' => 5,
		'NORM ZON (TABSK0>0 OR TABSK2>0)' => 6,
		'ELT DIN RES>29' => 4,
		'EXC DIN RES>19' => 5,
		'NORM DIN RES>9' => 6,
		#'ELT SIN' => 4,
		#'EXC SIN' => 5,
		#'NORM SIN' => 6,
	],

	// Set what tier to label these unique items.
	'uniques' => [
		//'vip' => '', // Amulet Of The Viper - Amulet (0)
		//'ulm' => '', // Steelshade - Armet (62)
		//'hfh' => '', // Hell Forge Hammer - Hammer (0)
		//'hst' => '', // Horadric Staff - Staff (0)
		//'qf1' => '', // KhalimFlail - Flail (0)
		//'msf' => '', // Staff Of Kings - Staff (0)
		//'qf2' => '', // SuperKhalimFlail - Flail (0)
		'cm1' => 3, // Annihilus - Charm (70)
		//'buc' => '', // Pelta Lunata - Buckler (2)
		//'ssd' => '', // Rixots Keen - Short Sword (2)
		//'clb' => '', // Felloak - Club (3)
		//'cap' => '', // War Bonnet - Cap (3)
		'dgr' => 5, // Gull - Dagger (4)
		//'sst' => '', // Bane Ash - Short Staff (5)
		'lbt' => 5, // Hotspur - Leather Boots (5)
		//'wnd' => '', // Iros Torch - Wand (5)
		//'scp' => '', // Knell Striker - Scepter (5)
		//'spc' => '', // Stoutnail - Spiked Club (5)
		//'hax' => '', // The Gnasher - Hand Axe (5)
		//'lgl' => '', // The Hand Of Broc - Gloves (5)
		//'scm' => '', // Blood Crescent - Scimitar (7)
		//'qui' => '', // Greyform - Quilted Armor (7)
		//'lbl' => '', // Lenyms Cord - Sash (7)
		'rin' => [ // Constricting Ring - Ring (95)
			'MFIND>19' => 5,
			'PRES>9' => 4,
			'AR>99' => 4,
			'CHSK236>0' => 3,
			'STAT27>19' => 5,
			'LIFE>19' => 5,
			'ALLSK>0' => 2,
		],
		//'sbw' => '', // Pluckeye - Short Bow (7)
		//'bar' => '', // Dimoaks Hew - Bardiche (8)
		//'lax' => '', // Fechmars Axe - Large Axe (8)
		//'spr' => '', // The Dragon Chang - Spear (8)
		'vgl' => 6, // Bloodfist - Heavy Gloves (9)
		//'mac' => '', // Crushflange - Mace (9)
		//'axe' => '', // Deathspade - Axe (9)
		//'lxb' => '', // Leadcrow - Light Crossbow (9)
		//'lst' => '', // Serpent Lord - Long Staff (9)
		//'sml' => '', // Umbral Disk - Small Shield (9)
		//'sbr' => '', // Krintizs Skewer - Saber (10)
		'amu' => [ // Metalgrid - Amulet (81)
			'IAS>19 FRW>19' => 4,
			'ALLSK>0 IAS>19' => 5,
			'ALLSK>0 RES>19' => 2,
			'AR>99' => 4,
			'REPLIFE>9' => 5,
			'CLSK1>1' => 3,
		],
		//'dir' => '', // The Diggler - Dirk (11)
		//'lea' => '', // Blinkbats Form - Leather Armor (12)
		//'vbt' => '', // Gorefoot - Heavy Boots (12)
		//'tri' => '', // Razortine - Trident (12)
		//'2hs' => '', // Shadowfang - 2-Handed Sword (12)
		//'vbl' => '', // Snakecord - Light Belt (12)
		//'crs' => '', // Azurewrath - Crystal Sword (13)
		//'flc' => '', // Gleamscythe - Falchion (13)
		//'lrg' => '', // Stormguild - Large Shield (13)
		//'hbw' => '', // Witherstring - Hunter�s Bow (13)
		//'hlm' => '', // Coif Of Glory - Helm (14)
		//'rng' => '', // Darkglow - Ring Mail (14)
		//'bax' => '', // Goreshovel - Broad Axe (14)
		//'ywn' => '', // Maelstromwrath - Yew Wand (14)
		//'vou' => '', // Steelgoad - Voulge (14)
		//'hla' => '', // The Centurion - Hard Leather (14)
		//'2ax' => '', // Bladebone - Double Axe (15)
		//'mst' => '', // Bloodrise - Morning Star (15)
		'mgl' => 5, // Chance Guards - Bracers (15)
		//'scl' => '', // Hawkmail - Scale Mail (15)
		'lbw' => 6, // Ravenclaw - Long Bow (15)
		//'spk' => '', // Swordback Hold - Spiked Shield (15)
		'skp' => 6, // Tarnhelm - Skull Cap (15)
		//'mbt' => '', // Treads Of Cthon - Chain Boots (15)
		//'stu' => '', // Twitchthroe - Studded Leather (16)
		//'brn' => '', // Bloodthief - Brandistock (17)
		//'fhl' => '', // Duskdeep - Full Helm (17)
		//'bsd' => '', // Griswolds Edge - Broad Sword (17)
		//'gsc' => '', // Rusthandle - Grand Scepter (17)
		//'chn' => '', // Sparking Mail - Chain Mail (17)
		//'kit' => '', // Steelclash - Kite Shield (17)
		//'mxb' => '', // Ichorsting - Crossbow (18)
		//'cst' => '', // Lazarus Spire - Gnarled Staff (18)
		//'tow' => '', // Bverrit Keep - Tower Shield (19)
		//'scy' => '', // Soul Harvest - Scythe (19)
		//'clm' => '', // Soulflay - Claymore (19)
		//'btx' => '', // The Chieftan - Battle Axe (19)
		//'kri' => '', // The Jade Tan Do - Kris (19)
		//'bwn' => '', // Gravenspine - Bone Wand (20)
		//'mbl' => '', // Nightsmoke - Belt (20)
		//'cbw' => '', // Piercerib - Composite Bow (20)
		//'msk' => '', // The Face Of Horror - Mask (20)
		//'am5' => '', // True Silver - Maiden Javelin (20)
		//'brs' => '', // Venomsward - Breast Plate (20)
		//'bsh' => '', // Wall Of The Eyeless - Bone Shield (20)
		//'mpi' => '', // Mindrend - Military Pick (21)
		//'fla' => '', // The Generals Tan Do Li Ga - Flail (21)
		//'bst' => '', // The Salamander - Battle Staff (21)
		//'bhm' => '', // Wormskull - Bone Helm (21)
		'tbt' => 5, // Goblin Toe - Light Plate Boots (22)
		//'lsd' => '', // Hellplague - Long Sword (22)
		//'spl' => '', // Iceblink - Splint Mail (22)
		//'spt' => '', // Lance Of Yaggai - Spetum (22)
		//'gis' => '', // Kinemils Awl - Giant Sword (23)
		'tgl' => 4, // Magefist - Light Gauntlets (23)
		//'wsp' => '', // Stormeye - War Scepter (23)
		//'mau' => '', // Bonesob - Maul (24)
		//'gax' => '', // Brainhew - Great Axe (25)
		//'ghm' => '', // Howltusk - Great Helm (25)
		//'bld' => '', // Irices Shard - Blade (25)
		//'sbb' => '', // Pullspite - Short Battle Bow (25)
		//'ob6' => '', // Tempest - Glowing Orb (25)
		//'pax' => '', // The Battlebranch - Poleaxe (25)
		//'bsw' => '', // Blacktongue - Bastard Sword (26)
		//'plt' => '', // Boneflesh - Plate Mail (26)
		//'ne6' => '', // Kalans Legacy - Mummified Trophy (26)
		//'flb' => '', // Ripsaw - Flamberge (26)
		//'gts' => '', // The Ward - Gothic Shield (26)
		//'lbb' => '', // Wizendraw - Long Battle Bow (26)
		'tbl' => 5, // Goldwrap - Heavy Belt (27)
		//'hxb' => '', // Hellcast - Heavy Crossbow (27)
		//'swb' => '', // Hellclap - Short War Bow (27)
		//'whm' => '', // Ironstone - War Hammer (27)
		//'9ar' => '', // Mage Slayer - Quhab (27)
		//'wax' => '', // Rakescar - War Axe (27)
		//'pik' => '', // The Tannr Gorerod - Pike (27)
		//'lwb' => '', // Blastbark - Long War Bow (28)
		'ba6' => 4, // Cyclopean Roar - Jawbone Visor (28)
		//'rxb' => '', // Doomspittle - Repeating Crossbow (28)
		//'ful' => '', // Goldskin - Full Plate Mail (28)
		'xap' => 6, // Peasent Crown - War Hat (28)
		//'8ss' => '', // Razorswitch - Jo Stalf (28)
		//'fld' => '', // Rockfleece - Field Plate (28)
		//'8sb' => '', // Skystrike - Edge Bow (28)
		//'wst' => '', // The Iron Jang Bong - War Staff (28)
		//'xui' => '', // The Spirit Shroud - Ghost Armor (28)
		//'gwn' => '', // Umes Lament - Grim Wand (28)
		//'aar' => '', // Victors Silk - AncientArmor (28)
		//'xuc' => '', // Visceratuant - Defender (28)
		//'hal' => '', // Woestave - Halberd (28)
		//'wsd' => '', // Culwens Point - War Sword (29)
		'hgl' => 5, // Frostburn - Gauntlets (29)
		//'ltp' => '', // Heavenly Garb - Light Plate (29)
		//'xlb' => '', // Infernostride - Demonhide Boots (29)
		//'dr2' => '', // Quetzalcoatl - Hawk Helm (29)
		//'gth' => '', // Rattlecage - Gothic Plate (29)
		//'pa3' => '', // Sankekur's Fall - Heraldic Shield (29)
		'xea' => 4, // Skin Of The Vipermagi - SerpentSkin Armor (29)
		//'gma' => '', // Steeldriver - Great Maul (29)
		'zlb' => 4, // String Of Ears - Demonhide Sash (29)
		//'hbt' => '', // Tearhaunch - Plate Boots (29)
		//'wsc' => '', // The Grim Reaper - War Scythe (29)
		//'gix' => '', // The Humongous - Giant Axe (29)
		//'gsd' => '', // The Patriarch - Great Sword (29)
		//'crn' => '', // Undead Crown - Crown (29)
		//'xlg' => '', // Venom Grip - Demonhide Gloves (29)
		//'9ss' => '', // Bloodletter - Gladius (30)
		//'9sm' => '', // Coldsteel Eye - Cutlass (31)
		'xml' => 5, // Mosers Blessed Circle - Round Shield (31)
		'8ls' => [ // Ribcracker - Quarterstaff (31)
			'ETH' => 4,
			'default' => 5,
		],
		//'8hb' => '', // Riphook - Razor Bow (31)
		'xkp' => 5, // Rockstopper - Sallet (31)
		//'xla' => '', // Skin Of The Flayerd One - Demonhide Armor (31)
		//'9sr' => '', // The Impaler - War Spear (31)
		//'xvg' => '', // Gravepalm - Sharkskin Gloves (32)
		//'8lx' => '', // Langer Briser - Arbalest (32)
		'zvb' => 4, // Razortail - Sharkskin Belt (32)
		//'9dg' => '', // Spineripper - Poignard (32)
		'xvb' => 5, // Waterwalk - Sharkskin Boots (32)
		//'9sb' => '', // Hexfire - Shamshir (33)
		//'xtu' => '', // Ironpelt - Tresllised Armor (33)
		//'9tr' => '', // Kelpie Snare - Fuscina (33)
		'8lb' => 6, // Kuko Shakaku - CedarBow (33)
		'9wn' => 5, // Suicide Branch - Burnt Wand (33)
		//'9cl' => '', // Dark Clan Crusher - Cudgel (34)
		'9fc' => 5, // Blade Of Ali Baba - Tulwar (35)
		//'9yw' => '', // Carin Shard - Petrified Wand (35)
		//'8cs' => '', // Chromatic Ire - Cedar Staff (35)
		//'xpk' => '', // Lance Guard - Barbed Shield (35)
		//'9br' => '', // Soulfeast Tine - War Fork (35)
		//'xng' => '', // Spiritforge - Linked Mail (35)
		'xlm' => [ // Stealskull - Casque (35)
			'ETH' => 4,
			'default' => 5,
		],
		//'xrg' => '', // Stormchaser - Scutum (35)
		//'9la' => '', // Warlord's Trust - Military Axe (35)
		'9bw' => 5, // Arm Of King Leoric - Tomb Wand (36)
		//'9ha' => '', // Coldkill - Hatchet (36)
		//'8cb' => '', // Endlesshail - Double Bow (36)
		//'xmg' => '', // Ghoulhide - Heavy Bracers (36)
		//'zmb' => '', // Gloomstrap - Mesh Belt (36)
		//'9di' => '', // Heart Carver - Rondel (36)
		//'8mx' => '', // Pus Spiter - Siege Crossbow (36)
		'xmb' => 4, // Silkweave - Mesh Boots (36)
		//'xcl' => '', // Crow Caw - Tigulated Mail (37)
		//'9cr' => '', // Ginther's Rift - Dimensional Blade (37)
		'9st' => [
			'ETH' => 4,
			'default' => 5,
		], // Hone Sundan - Yari (37)
		//'9sc' => '', // Zakarum's Hand - Rune Scepter (37)
		//'9kr' => '', // Blackbog's Sharp - Cinquedeas (38)
		//'xhl' => '', // Darksight Helm - Basinet (38)
		//'9sp' => '', // Fleshrender - Barbed Club (38)
		'xhn' => [ // Shaftstop - Mesh Armor (38)
			'ETH' => 4,
			'default' => 5,
		],
		//'9qs' => '', // The Fetid Sprinkler - Holy Water Sprinkler (38)
		//'xit' => '', // Tiamat's Rebuke - Dragon Shield (38)
		//'hbl' => '', // Bladebuckle - Girdle (39)
		//'9ax' => '', // Butcher's Pupil - Cleaver (39)
		'9bs' => [
			'ETH' => 5,
			'default' => 6,
		], // Headstriker - Battle Sword (39)
		//'9ba' => '', // Spellsteel - Bearded Axe (39)
		//'9p9' => '', // Spire Of Honor - Lance (39)
		//'9ma' => '', // Sureshrill Frost - Flanged Mace (39)
		//'8bs' => '', // Warpspear - Gothic Staff (39)
		//'8s8' => '', // Whichwild String - Short Siege Bow (39)
		//'9gw' => '', // Blackhand Key - Grave Wand (41)
		//'xsk' => '', // Blackhorn's Face - Death Mask (41)
		//'8hx' => '', // Buriza-Do Kyanon - Balista (41)
		//'8l8' => '', // Cliffkiller - Long Siege Bow (41)
		'xrs' => [
			'ETH' => 4,
			'default' => 5,
		], // Duriel's Shell - Cuirass (41)
		'xsh' => 5, // Lidless Wall - Grim Shield (41)
		//'9ls' => '', // Plague Bearer - Rune Sword (41)
		//'8ws' => '', // Skullcollector - Rune Staff (41)
		//'9bt' => '', // Stormrider - Tabar (41)
		//'9bl' => '', // Stormspike - Stilleto (41)
		//'9b7' => '', // The Meat Scraper - Lochaber Axe (41)
		'xh9' => [
			'ETH' => 3,
			'default' => 5,
		], // Vampiregaze - Grim Helm (41)
		'baa' => 4, // Arreat's Face - Slayer Guard (42)
		//'9s8' => '', // Athena's Wrath - Battle Scythe (42)
		//'9vo' => '', // Blackleach Blade - Bill (42)
		//'9ga' => '', // Boneslayer Blade - Gothic Axe (42)
		//'92h' => '', // Crainte Vomir - Espadon (42)
		'9tw' => 5, // Bartuc's Cut Throat - Runic Talons (42)
		//'9ws' => '', // Hand Of Blessed Light - Divine Scepter (42)
		'pa9' => 4, // Herald Of Zakarum - Aerin Shield (42)
		'nea' => 5, // Homunculus - Heirophant Trophy (42)
		'dra' => 5, // Jalal's Mane - Dream Spirit (42)
		//'xtg' => '', // Lavagout - Battle Guantlets (42)
		'am7' => 5, // Lycander's Aim - Ceremonial Bow (42)
		//'am9' => '', // Lycander's Flank - Ceremonial Pike (42)
		//'9mt' => '', // Moonfall - Jagged Star (42)
		//'drf' => '', // Nightmares Feast - Dream Spirit (42)
		'xpl' => [
			'ETH' => 4,
			'default' => 5,
		], // Skullder's Ire - Russet Armor (42)
		'ztb' => 5, // Snowclash - Battle Belt (42)
		//'9wd' => '', // The Atlantian - Ancient Sword (42)
		'oba' => 4, // The Oculus - Swirling Crystal (42)
		'ama' => [ // Titan's Revenge - Ceremonial Javelin (42)
			'ETH' => 3,
			'default' => 4,
		],
		'xtb' => 3, // Wartraveler - Battle Boots (42)
		//'9cm' => '', // Bing Sz Wang - Dacian Falx (43)
		//'9wh' => '', // Earthshaker - Battle Hammer (43)
		//'92a' => '', // Islestrike - Twin Axe (43)
		//'8sw' => '', // Magewrath - Rune Bow (43)
		//'9pa' => '', // Pierre Tombale Couant - Partizan (43)
		//'9tk' => '', // Deathbit - Battle Dart (44)
		//'9h9' => '', // Husoldal Evo - Bec-de-Corbin (44)
		//'xow' => '', // Kerke's Sanctuary - Pavise (44)
		//'9gs' => '', // The Vile Husk - Tusk Sword (44)
		'xhm' => 4, // Valkiry Wing - Winged Helm (44)
		//'9fl' => '', // Baezil's Vortex - Knout (45)
		//'9b9' => '', // Cloudcrack - Gothic Sword (45)
		//'9wc' => '', // Grim's Burning Dead - Grim Scythe (45)
		'xlt' => [
			'ETH' => 4,
			'default' => 5,
		], // Guardian Angel - Templar Coat (45)
		//'ulb' => '', // Merman's Speed - Wyrrnhide Boots (45)
		//'9mp' => '', // Pompe's Wrath - Crowbill (45)
		//'9gm' => '', // The Gavel Of Pain - Martel De Fer (45)
		//'9gi' => '', // The Minataur - Ancient Axe (45)
		//'8lw' => '', // Godstrike Arch - Gothic Bow (46)
		//'9fb' => '', // Todesfaelle Flamme - Zweihander (46)
		'xhb' => 4, // Gorerider - War Boots (47)
		//'xhg' => '', // Hellmouth - War Gauntlets (47)
		'zhb' => 4, // Thudergod's Vigor - War Belt (47)
		//'9m9' => '', // Bloodtree Stump - War Club (48)
		//'9wa' => '', // Guardian Naga - Naga (48)
		//'9gd' => '', // Swordguard - Executioner Sword (48)
		//'xld' => '', // Toothrow - Sharktooth Armor (48)
		'xrn' => [
			'ETH' => 4,
			'default' => 5,
		], // Crown Of Thieves - Grand Crown (49)
		//'8rx' => '', // Demon Machine - Chu-Ko-Nu (49)
		'jew' => 3, // Rainbow Facet - Jewel (49)
		//'xts' => '', // Radimant's Sphere - Ancient Shield (50)
		//'xth' => '', // Atma's Wail - Embossed Plate (51)
		'uvc' => 4, // Nosferatu's Coil - Vampirefang Belt (51)
		'xtp' => 6, // Que-Hegan's Wisdon - Mage Plate (51)
		//'xul' => '', // Black Hades - Chaos Armor (53)
		//'xar' => '', // Corpsemourn - Ornate Armor (55)
		//'9ta' => '', // The Scalper - Francisca (57)
		'7cr' => 4, // Azurewrath - Phase Blade (85)
		'7ws' => 3, // Ironward - Caduceus (60)
		//'uml' => '', // Blackoak Shield - Luna (61)
		//'7sb' => '', // Bloodmoon - Elegant Blade (61)
		//'bad' => '', // Demonhorn's Edge - Destroyer Helm (61)
		'7sc' => [
			2 => 4,
			'default' => 5,
		], // The Reedeemer - Mighty Scepter (72)
		'7dg' => 4, // Wizardspike - Bone Knife (61)
		'cm3' => 4, // Gheed's Fortune - Charm (62)
		//'7bl' => '', // Ghostflame - Legend Spike (62)
		'uap' => 3, // Harlequin Crest - Shako (62)
		//'drb' => '', // Cerebus - Blood Spirit (63)
		//'7mp' => '', // Cranebeak - War Spike (63)
		//'7sp' => '', // Demonlimb - Tyrant Club (63)
		'umc' => 4, // Verdugo's Hearty Cord - Mithril Coil (63)
		'7o7' => [ // Bonehew - Ogre Axe (64)
			'ETH' => 4,
			'default' => 5,
		],
		'nef' => [
			'TABSK17>2' => 2,
			'default' => 3,
		], // Darkforge Spawn - Bloodlord Skull (64)
		'7fl' => [
			'IAS>29' => 3,
			'default' => 4,
		], // Stormlash - Scourge (82)
		'uvb' => [ // Sandstorm Trek - Scarabshell Boots (64)
			'ETH' => 3,
			'default' => 4,
		],
		//'amd' => '', // Stoneraven - Matriarchal Spear (64)
		//'7mt' => '', // Baranar's Star - Devil Star (65)
		//'7sm' => '', // Djinnslayer - Ataghan (65)
		//'uh9' => '', // Giantskull - Bone Visage (65)
		//'uld' => '', // Leviathan - Kraken Shell (65)
		//'7tw' => '', // Stalkers Cull - Runic Talons (65)
		//'6sw' => '', // Grief - Ward Bow (65)
		'7gw' => 1, // Deaths's Web - Unearthed Wand (66)
		//'7bt' => '', // Hellslayer - Decapitator (66)
		//'7wb' => '', // Jadetalon - Wrist Sword (66)
		//'umb' => '', // Marrowwalk - Boneweave Boots (66)
		//'6cs' => '', // Ondal's Wisdom - Elder Staff (66)
		//'uul' => '', // Steel Carapice - Shadow Plate (66)
		//'7lw' => '', // Firelizard's Talons - Feral Claws (67)
		'uhm' => 2, // Nightwing's Veil - Spired Helm (73)
		//'7ha' => '', // Razoredge - Tomahawk (67)
		//'drd' => '', // Spiritkeeper - Earth Spirit (67)
		//'7s7' => '', // Demon's Arch - Balrog Spear (68)
		'7kr' => 5, // Fleshripper - Fanged Knife (68)
		'7b8' => [
			'ETH' => 4,
			'default' => 5,
		], // Lacerator - Winged Axe (68)
		//'ned' => '', // Martyr - Overseer Skull (68)
		//'7cl' => '', // Nord's Tenderizer - Truncheon (68)
		//'uts' => '', // Spirit Ward - Ward (68)
		//'7wh' => '', // Schaefer's Hammer - Legendary Mallet (79)
		'7m7' => [
			'ETH' => 4,
			'default' => 5,
		], // Windhammer - Ogre Maul (68)
		//'7b7' => '', // Doombringer - Champion Sword (69)
		//'6l7' => '', // Eaglehorn - Crusader Bow (69)
		//'7gm' => '', // The Cranium Basher - Thunder Maul (87)
		//'7p7' => '', // Steelpillar - War Pike (69)
		'amf' => [ // Thunderstroke - Matriarchal Javelin (69)
			'TABSK2>2' => 4,
			'default' => 5,
		],
		'7wa' => [ // Deathcleaver - Berserker Axe (70)
			'ETH' => 1,
			'default' => 2,
		],
		//'7ls' => '', // Frostwind - Cryptic Sword (70)
		//'7ts' => '', // Gargoyle's Bite - Winged Harpoon (70)
		//'7ta' => '', // Gimmershred - Flying Axe (70)
		'7ga' => 3, // Messerschmidt's Reaver - Champion Axe (70)
		//'utg' => '', // Occultist - Crusader Guantlets (70)
		//'upk' => '', // Spike Thorn - Blade Barrier (70)
		'uhg' => 3, // Steelrend - Ogre Gauntlets (70)
		//'7wc' => '', // Stormspire - Giant Thresher (70)
		//'amb' => '', // Bloodraven's Charge - Matriarchal Bow (71)
		//'7gs' => '', // Flamebellow - Balrog Blade (71)
		//'6rx' => '', // Gutsiphon - Demon Crossbow (71)
		'uhb' => 3, // Shadowdancer - Myrmidon Greaves (71)
		//'7br' => '', // Viperfork - War Fork (71)
		//'nee' => '', // Boneflame - Succubae Skull (72)
		//'obc' => '', // Eschuta's Temper - Eldritch Orb (72)
		//'7cm' => '', // Leoric's Mithril Blade - Highland Blade (72)
		'72a' => [
			'ETH SOCK=5' => 4,
			'default' => 5,
		], // Runemaster - Ettin Axe (72)
		'obf' => 1, // Fathom - Dimensional Shard (73)
		'uit' => 4, // Stormshield - Monarch (73)
		'6lw' => 3, // Windforce - Hydra Bow (73)
		//'7qs' => '', // Akarats Devotion - Seraph Rod (74)
		//'7ba' => '', // Ethereal Edge - Silver-edged Axe (74)
		//'dre' => '', // Ravenlore - Sky Spirit (74)
		//'umg' => '', // Souldrain - Vambraces (74)
		'uar' => 1, // Tyrael's Might - Sacred Armor (84)
		//'7st' => '', // Uldyssian's Awakening - Ghost Spear (74)
		//'7gi' => '', // Executioner's Justice - Glorious Axe (75)
		'ush' => [ // Headhunter's Glory - Troll Nest (75)
			3 => 3,
			'default' => 4,
		],
		'cm2' => 3, // Hellfire Torch - Charm (75)
		'uui' => [ // Ormus' Robes - Dusk Shroud (75)
			'(SK49>0 OR SK53>0 OR SK52>0 OR SK59>0)' => 2,
			'default' => 4,
		],
		//'utp' => '', // Purgatory - Archon Plate (75)
		'7s8' => [ // The Reaper's Toll - Thresher (75)
			'ETH' => 2,
			'default' => 4,
		],
		'7bk' => [
			'ETH' => 4,
			'default' => 5,
		], // Warshrike - Winged Knife (75)
		'uvg' => 4, // Dracul's Grasp - Vampirebone Gloves (76)
		'ci3' => 1, // Griffon's Eye - Diadem (76)
		//'6hx' => '', // Hellrack - Colossus Crossbow (76)
		//'uow' => '', // Medusa's Gaze - Aegis (76)
		//'7gl' => '', // Wraithflight - Ghost Glaive (76)
		//'ame' => '', // Zeraes Resolve - Matriarchal Pike (76)
		//'pac' => '', // Alma Negra - Sacred Rondache (77)
		//'bae' => '', // Halaberd's Reign - Conqueror Crown (77)
		'ci2' => 5, // Kira's Guardian - Tiara (77)
		//'baf' => '', // Raekors Virtue - Guardian Crown (78)
		//'7cs' => '', // Shadowkiller - Battle Cestus (78)
		//'7bw' => '', // Boneshade - Lich Wand (79)
		//'bac' => '', // Wolfhowl - Fury Visor (79)
		'ulc' => 2, // Arachnid Mesh - Spiderweb Sash (80)
		//'6bs' => '', // Brimstone Rain - Shillelah (80)
		//'pae' => '', // Dragonscale - Zakarum Shield (80)
		//'t53' => '', // Fallen Gardens Map - T53 (80)
		//'7fb' => '', // Odium - Colossal Sword (80)
		//'t52' => '', // Warlord Of Blood Map - T52 (80)
		//'t51' => '', // Zhar The Mad Map - T51 (80)
		'7sr' => [
			'ETH' => 4,
			'default' => 5,
		], // Arioc's Needle - Hyperion Spear (81)
		//'7gd' => '', // The Grandfather - Colossus Blade (81)
		'urn' => [ // Crown Of Ages - Corona (82)
			2 => 1,
			'default' => 2,
		],
		'6ws' => 3, // Mang Song's Lesson - Archon Staff (82)
		'usk' => [ // Andariel's Visage - Demonhead (83)
			'ETH' => 2,
			'default' => 3,
		],
		'7pa' => [ // Tomb Reaver - Cryptic Axe (84)
			'ETH SOCK=3' => 1,
			'default' => 3,
		],
		//'7qr' => '', // Aidans Scar - Scissors Suwayyah (85)
		'upl' => [
			'ALLSK>1' => 4,
			'default' => 5,
		], // Arkaine's Valor - Balrog Skin (85)
		//'uth' => '', // Dark Abyss - Lacquered Plate (85)
		//'7bs' => '', // Hadriels Hand - Conquest Sword (85)
		//'utb' => '', // Itheraels Path - Mirrored Boots (85)
		//'uhl' => '', // Overlords Helm - Giant Conch (85)
		'utu' => [
			'ETH' => 4,
			'default' => 5,
		], // The Gladiator's Bane - Wire Fleece (85)
		//'rbe' => '', // Band Of Skulls - Troll Belt (90)
		//'rar' => '', // Cage Of The Unsullied - Boneweave (90)
		//'ram' => '', // The Third Eye - Amulet (90)
	],

	// Set what tier to label these set items.
	'sets' => [
		//'vbl' => '', // Arctic Binding - Light Belt (2)
		//'qui' => '', // Arctic Furs - Quilted Armor (2)
		//'swb' => '', // Arctic Horn - Short War Bow (2)
		//'tgl' => '', // Iratha's Cuff - Light Gauntlets (15)
		//'2ax' => '', // Berserker's Hatchet - Double Axe (3)
		//'spl' => '', // Berserker's Hauberk - Splint Mail (3)
		//'hlm' => '', // Berserker's Headgear - Helm (3)
		//'buc' => '', // Hsarus' Iron Fist - Buckler (3)
		//'mbt' => '', // Hsarus' Iron Heel - Chain Boots (3)
		//'mbl' => '', // Hwanin's Seal - Belt (35)
		//'sml' => '', // Cleglaw's Claw - Small Shield (4)
		//'mgl' => '', // Cleglaw's Pincers - Chain Gloves (4)
		//'lsd' => '', // Cleglaw's Tooth - Long Sword (4)
		//'cap' => '', // McAuley's Paragon - Cap (25)
		//'tbl' => '', // Iratha's Cord - Heavy Belt (15)
		//'dgr' => '', // Infernal Spire - Dagger (5)
		//'lbl' => '', // Death's Guard - Sash (6)
		//'lgl' => '', // Death's Hand - Leather Gloves (6)
		//'wsd' => '', // Death's Touch - War Sword (6)
		//'hgl' => 6, // Sigon's Gage - Gauntlets (6)
		//'tow' => 6, // Sigon's Guard - Tower Shield (6)
		//'hbt' => 6, // Sigon's Sabot - Greaves (6)
		//'gth' => 6, // Sigon's Shelter - Gothic Plate (6)
		//'ghm' => 6, // Sigon's Visor - Great Helm (6)
		//'hbl' => 6, // Sigon's Wrap - Plated Belt (6)
		//'brs' => '', // Isenhart's Case - Breast Plate (8)
		//'fhl' => '', // Isenhart's Horns - Full Helm (8)
		//'bsd' => '', // Isenhart's Lightbrand - Broad Sword (8)
		//'gts' => '', // Isenhart's Parry - Gothic Shield (8)
		//'gsc' => '', // Civerb's Cudgel - Grand Scepter (9)
		//'amu' => '', // Tal Rasha's Adjudication - Amulet (67)
		//'lrg' => '', // Civerb's Ward - Large Shield (9)
		//'chn' => '', // Cathan's Mesh - Chain Mail (11)
		//'bst' => '', // Cathan's Rule - Battle Staff (11)
		'rin' => [ // Bul-Kathos' Death Band - Ring (69)
			'ALLSK>0' => 2,
		],
		//'msk' => '', // Cathan's Visage - Mask (11)
		//'rng' => '', // Angelic Mantle - Ring Mail (12)
		//'sbr' => '', // Angelic Sickle - Sabre (12)
		//'vbt' => '', // McAuley's Riprap - Heavy Boots (20)
		//'lea' => '', // Vidala's Ambush - Leather Armor (14)
		//'lbb' => '', // Vidala's Barb - Long Battle Bow (14)
		//'tbt' => '', // Vidala's Fetlock - Light Plated Boots (14)
		//'wst' => '', // Arcanna's Deathwand - War Staff (15)
		//'ltp' => '', // Arcanna's Flesh - Light Plate (15)
		//'skp' => '', // Arcanna's Head - Skull Cap (15)
		//'crn' => '', // Milabrega's Diadem - Crown (17)
		//'kit' => '', // Milabrega's Orb - Kite Shield (17)
		//'aar' => '', // Milabrega's Robe - Ancient Armor (17)
		//'wsp' => '', // Milabrega's Rod - War Scepter (17)
		//'stu' => '', // Cow King's Hide - Studded Leather (18)
		//'mpi' => '', // Tancred's Crowbill - Military Pick (20)
		//'lbt' => '', // Tancred's Hobnails - Boots (20)
		//'bhm' => '', // Tancred's Skull - Bone Helm (20)
		//'ful' => '', // Tancred's Spine - Full Plate Mail (20)
		//'xap' => '', // Cow King's Horns - War Hat (25)
		//'bwn' => '', // McAuley's Superstition - Bone Wand (25)
		//'xmb' => '', // Natalya's Soul - Mesh Boots (25)
		//'9vo' => '', // Hwanin's Justice - Bill (28)
		//'vgl' => '', // McAuley's Taboo - Heavy Gloves (28)
		//'ci0' => '', // Naj's Circlet - Circlet (28)
		'zhb' => 5, // Immortal King's Detail - War Belt (29)
		//'xlb' => '', // Rite Of Passage - Demonhide Boots (29)
		//'xml' => '', // Wihtstan's Guard - Round Shield (29)
		//'xcl' => '', // Hwanin's Refuge - Tigulated Mail (30)
		//'xhg' => '', // Immortal King's Forge - War Gauntlets (30)
		//'xhb' => '', // Immortal King's Pillar - War Boots (31)
		//'xtg' => '', // M'avina's Icy Clutch - Battle Gauntlets (32)
		'xhm' => 4, // Guillaume's Face - Winged Helm (34)
		//'dr8' => '', // Aldur's Stony Gaze - Hunter's Guise (36)
		//'xvg' => '', // Magnus' Skin - Sharkskin Gloves (37)
		//'9mt' => '', // Aldur's Gauntlet - Jagged Star (42)
		//'ztb' => '', // Wilhelm's Pride - Battle Belt (42)
		'xhl' => 6, // Sazabi's Mental Sheath - Basinet (43)
		//'uui' => '', // Spiritual Custodian - Dusk Shroud (43)
		//'xrs' => '', // Haemosu's Adament - Cuirass (44)
		'xtb' => 4, // Aldur's Advance - Battle Boots (45)
		//'xar' => '', // Griswold's Heart - Ornate Plate (45)
		//'xrn' => '', // Hwanin's Splendor - Grand Crown (45)
		//'zvb' => '', // M'avina's Tenet - Sharkskin Belt (45)
		'xmg' => 4, // Trang-Oul's Claws - Heavy Bracers (45)
		'ba5' => 5, // Immortal King's Will - Avenger Guard (47)
		'utc' => 4, // Trang-Oul's Girth - Troll Belt (47)
		//'xul' => '', // Trang-Oul's Scales - Chaos Armor (49)
		'7ws' => [
			4 => 4,
			'default' => 5,
		], // Griswolds's Redemption - Caduceus (53)
		'zmb' => 4, // Tal Rasha's Fire-Spun Cloth - Mesh Belt (53)
		//'7fb' => '', // Bul-Kathos' Tribal Guardian - Colossal Sword (54)
		'ne9' => 4, // Trang-Oul's Wing - Cantor Trophy (54)
		//'ci3' => '', // M'avina's True Sight - Diadem (59)
		//'xh9' => '', // Natalya's Totem - Grim Helm (59)
		//'7gd' => '', // Bul-Kathos' Sacred Charge - Colossus Blade (61)
		'ulg' => 5, // Laying Of Hands - Bramble Mitts (63)
		//'umc' => '', // Credendum - Mithril Coil (65)
		'oba' => 4, // Tal Rasha's Lidless Eye - Swirling Crystal (65)
		//'uh9' => '', // Trang-Oul's Guise - Bone Visage (65)
		'xsk' => 4, // Tal Rasha's Horadric Crest - Death Mask (66)
		//'upl' => '', // Sazabi's Ghost Liberator - Balrog Skin (67)
		//'7ma' => '', // Dangoon's Teaching - Reinforced Mace (68)
		'paf' => 5, // Griswold's Honor - Vortex Shield (68)
		'urn' => 5, // Griswold's Valor - Corona (69)
		//'uhm' => '', // Ondal's Almighty - Spired Helm (69)
		//'amc' => '', // M'avina's Caster - Grand Matron Bow (70)
		//'uld' => '', // M'avina's Embrace - Kraken Shell (70)
		//'ult' => '', // Naj's Light Plate - Hellforge Plate (71)
		'uth' => 3, // Tal Rasha's Guardianship - Lacquered Plate (71)
		//'ucl' => '', // Natalya's Shadow - Loricated Mail (73)
		//'7ls' => '', // Sazabi's Cobalt Redeemer - Cryptic Sword (73)
		//'uul' => '', // Aldur's Deception - Shadow Plate (76)
		'uar' => 4, // Immortal King's Soul Cage  - Sacred Armor (76)
		//'7m7' => '', // Immortal King's Stone Crusher - Ogre Maul (76)
		//'6cs' => '', // Naj's Puzzler - Elder Staff (78)
		//'7qr' => '', // Natalya's Mark - Scissors Suwayyah (79)
		//'uts' => '', // Heaven's Taebaek - Ward (81)
	],

	// Set what tier to label these base armor items.
	'armors' => [
		//'aar' => [], // Ancient Armor - Tors (0)
		//'mbl' => [], // Belt(M) - Belt (0)
		//'bhm' => [], // Bone Helm - Helm (0)
		//'bsh' => [], // Bone Shield - Shie (0)
		//'mgl' => [], // Bracers(M) - Glov (0)
		//'brs' => [], // Breast Plate - Tors (0)
		//'buc' => [], // Buckler - Shie (0)
		//'cap' => [], // Cap/hat - Helm (0)
		//'mbt' => [], // Chain Boots - Boot (0)
		//'chn' => [], // Chain Mail - Tors (0)
		//'crn' => [], // Crown - Helm (0)
		//'fld' => [], // Field Plate - Tors (0)
		//'fhl' => [], // Full Helm - Helm (0)
		//'ful' => [], // Full Plate Mail - Tors (0)
		//'hgl' => [], // Gaunlets(H) - Glov (0)
		//'hbl' => [], // Girdle(H) - Belt (0)
		//'lgl' => [], // Gloves(L) - Glov (0)
		//'gth' => [], // Gothic Plate - Tors (0)
		//'gts' => [], // Gothic Shield - Shie (0)
		//'ghm' => [], // Great Helm - Helm (0)
		//'hla' => [], // Hard Leather Armor - Tors (0)
		//'tbl' => [], // Heavy Belt - Belt (0)
		//'vbt' => [], // Heavy Boots - Boot (0)
		//'vgl' => [], // Heavy Gloves - Glov (0)
		//'hlm' => [], // Helm - Helm (0)
		'kit' => [ // Kite Shield - Shie (0)
			3 => 6,
			0 => 6,
		],
		//'lrg' => [], // Large Shield - Shie (0)
		//'lea' => [], // Leather Armor - Tors (0)
		//'lbt' => [], // Leather Boots - Boot (0)
		//'vbl' => [], // Light Belt - Belt (0)
		//'tgl' => [], // Light Gauntlets - Glov (0)
		'ltp' => [ // Light Plate - Tors (0)
			2 => 6,
			0 => 6,
		],
		//'tbt' => [], // Light Plate Boots - Boot (0)
		//'msk' => [], // Mask - Helm (0)
		//'hbt' => [], // Plate Boots - Boot (0)
		//'plt' => [], // Plate Mail - Tors (0)
		//'qui' => [], // Quilted Armor - Tors (0)
		//'rng' => [], // Ring Mail - Tors (0)
		//'lbl' => [], // Sash(L) - Belt (0)
		//'scl' => [], // Scale Mail - Tors (0)
		//'skp' => [], // Skull Cap - Helm (0)
		//'sml' => [], // Small Shield - Shie (0)
		//'spk' => [], // Spiked Shield - Shie (0)
		//'spl' => [], // Splint Mail - Tors (0)
		'stu' => [ // Studded Leather - Tors (0)
			2 => 6,
			0 => 6,
		],
		//'tow' => [], // Tower Shield - Shie (0)
		//'ba1' => [], // Jawbone Cap - Phlm (3)
		//'ne1' => [], // Preserved Head - Head (3)
		//'pa1' => [], // Targe - Ashd (3)
		//'dr1' => [], // Wolf Head - Pelt (3)
		//'ba2' => [], // Fanged Helm - Phlm (6)
		//'dr2' => [], // Hawk Helm - Pelt (6)
		//'pa2' => [], // Rondache - Ashd (6)
		//'ne2' => [], // Zombie Head - Head (6)
		//'dr3' => [], // Antlers - Pelt (12)
		//'pa3' => [], // Heraldic Shield - Ashd (12)
		//'ba3' => [], // Horned Helm - Phlm (12)
		//'ne3' => [], // Unraveller Head - Head (12)
		//'pa4' => [], // Aerin Shield - Ashd (15)
		//'ba4' => [], // Assault Helmet - Phlm (15)
		//'dr4' => [], // Falcon Mask - Pelt (15)
		//'ne4' => [], // Gargoyle Head - Head (15)
		//'ci0' => [], // Circlet - Circ (16)
		//'ba5' => [], // Avenger Guard - Phlm (18)
		//'pa5' => [], // Crown Shield - Ashd (18)
		//'ne5' => [], // Demon Head - Head (18)
		//'dr5' => [], // Spirit Mask - Pelt (18)
		//'xlg' => [], // Demonhide Gloves - Glov (21)
		//'xuc' => [], // Defender - Shie (22)
		//'xui' => [], // Ghost Armor - Tors (22)
		//'xap' => [], // War Hat - Helm (22)
		//'xlb' => [], // Demonhide Boots - Boot (24)
		//'zlb' => [], // Demonhide Sash - Belt (24)
		//'ne6' => [], // Mummified Trophy - Head (24)
		//'xea' => [], // Serpentskin Armor - Tors (24)
		//'xts' => [], // Ancient Shield - Shie (25)
		//'xpk' => [], // Barbed Shield - Shie (25)
		//'xhl' => [], // Basinet - Helm (25)
		//'ztb' => [], // Battle Belt - Belt (25)
		//'xtb' => [], // Battle Boots - Boot (25)
		//'xtg' => [], // Battle Gauntlets - Glov (25)
		//'xlm' => [], // Casque - Helm (25)
		//'xul' => [], // Chaos Armor - Tors (25)
		//'xrs' => [], // Cuirass - Tors (25)
		//'xsk' => [], // Death Mask - Helm (25)
		//'xla' => [], // Demonhide Armor - Tors (25)
		'xit' => [ // Dragon Shield - Shie (25)
			3 => 6,
			4 => 5,
			0 => 6,
		],
		//'xth' => [], // Embossed Plate - Tors (25)
		//'xrn' => [], // Grand Crown - Helm (25)
		//'xh9' => [], // Grim Helm - Helm (25)
		//'xsh' => [], // Grim Shield - Shie (25)
		//'xmg' => [], // Heavy Bracers - Glov (25)
		//'ba6' => [], // Jawbone Visor - Phlm (25)
		//'xng' => [], // Linked Mail - Tors (25)
		'xtp' => [ // Mage Plate - Tors (25)
			3 => 4,
			2 => 5,
			0 => 5,
		],
		//'xhn' => [], // Mesh Armor - Tors (25)
		//'zmb' => [], // Mesh Belt - Belt (25)
		//'xmb' => [], // Mesh Boots - Boot (25)
		//'xar' => [], // Ornate Armor - Tors (25)
		//'xow' => [], // Pavise - Shie (25)
		//'xml' => [], // Round Shield - Shie (25)
		//'xpl' => [], // Russet Armor - Tors (25)
		//'xkp' => [], // Sallet - Helm (25)
		//'xrg' => [], // Scutum - Shie (25)
		//'zvb' => [], // Sharkskin Belt - Belt (25)
		//'xvb' => [], // Sharkskin Boots - Boot (25)
		//'xvg' => [], // Sharkskin Gloves - Glov (25)
		//'xld' => [], // Sharktooth Armor - Tors (25)
		//'xlt' => [], // Templar Coat - Tors (25)
		//'xcl' => [], // Tigulated Mail - Tors (25)
		'xtu' => [ // Trellised Armor - Tors (25)
			3 => 4,
			2 => 5,
			0 => 5,
		],
		//'zhb' => [], // War Belt - Belt (25)
		//'xhb' => [], // War Boots - Boot (25)
		//'xhg' => [], // War Gauntlets - Glov (25)
		//'xhm' => [], // Winged Helm - Helm (25)
		//'pa6' => [], // Akaran Targe - Ashd (26)
		//'dr6' => [], // Alpha Helm - Pelt (26)
		//'ne7' => [], // Fetish Trophy - Head (29)
		//'dr8' => [], // Hunter's Guise - Pelt (29)
		//'ba7' => [], // Lion Helm - Phlm (29)
		//'ba8' => [], // Rage Mask - Phlm (29)
		//'pa7' => [], // Akaran Rondache - Ashd (30)
		//'dr7' => [], // Griffon Headress - Pelt (30)
		//'dr9' => [], // Sacred Feathers - Pelt (32)
		//'ba9' => [], // Savage Helmet - Phlm (32)
		//'ne8' => [], // Sexton Trophy - Head (33)
		//'pa8' => [], // Protector Shield - Ashd (34)
		//'ne9' => [], // Cantor Trophy - Head (36)
		//'pa9' => [], // Guilded Shield - Ashd (38)
		//'ci1' => [], // Coronet - Circ (39)
		//'uhl' => [], // Giant Conch - Helm (40)
		//'nea' => [], // Heirophant Trophy - Head (40)
		//'baa' => [], // Slayer Guard - Phlm (40)
		//'paa' => [], // Royal Shield - Ashd (41)
		//'dra' => [], // Totemic Mask - Pelt (41)
		//'ulg' => [], // Bramble Mitts - Glov (42)
		//'uuc' => [], // Heater - Shie (43)
		//'uap' => [], // Shako - Helm (43)
		//'neb' => [], // Minion Skull - Head (44)
		//'bab' => [], // Carnage Helm - Phlm (45)
		//'uml' => [], // Luna - Shie (45)
		//'ulb' => [], // Wyrmhide Boots - Boot (45)
		//'drb' => [], // Blood Spirt - Pelt (46)
		//'ulc' => [], // Spiderweb Sash - Belt (46)
		//'uhn' => [], // Boneweave - Tors (47)
		//'rar' => [], // Boneweave [S] - Tors (47)
		//'ukp' => [], // Hydraskull - Helm (47)
		//'pab' => [], // Sacred Targe - Ashd (47)
		//'uvg' => [], // Vampirebone Gloves - Glov (47)
		//'urg' => [], // Hyperion - Shie (48)
		'uui' => [ // Dusk Shroud - Tors (49)
			3 => 3,
			4 => 4,
			2 => 5,
			0 => 4,
		],
		//'bac' => [], // Fury Visor - Phlm (49)
		//'ned' => [], // Overseer Skull - Head (49)
		//'uvb' => [], // Scarabshell Boots - Boot (49)
		//'neg' => [], // Hellspawn Skull - Head (50)
		//'uea' => [], // Wyrmhide - Tors (50)
		//'ulm' => [], // Armet - Helm (51)
		//'upk' => [], // Blade Barrier - Shie (51)
		//'ula' => [], // Scarab Husk - Tors (51)
		//'drc' => [], // Sun Spirit - Pelt (51)
		//'umg' => [], // Vambraces - Glov (51)
		//'uvc' => [], // Vampirefang Belt - Belt (51)
		//'pac' => [], // Sacred Rondache - Ashd (52)
		//'ci2' => [], // Tiara - Circ (52)
		'utu' => [ // Wire Fleece - Tors (53)
			3 => 3,
			4 => 4,
			2 => 5,
			0 => 4,
		],
		//'umb' => [], // Boneweave Boots - Boot (54)
		//'bad' => [], // Destroyer Helm - Phlm (54)
		//'ung' => [], // Diamond Mail - Tors (54)
		'uit' => [ // Monarch - Shie (54)
			4 => 4,
			3 => 3,
			0 => 4,
		],
		//'pad' => [], // Ancient Shield - Ashd (55)
		//'usk' => [], // Demonhead - Helm (55)
		//'ucl' => [], // Loricated Mail - Tors (55)
		//'urs' => [], // Great Hauberk - Tors (56)
		//'umc' => [], // Mithril Coil - Belt (56)
		//'upl' => [], // Balrog Skin - Tors (57)
		//'utg' => [], // Crusader Gauntlets - Glov (57)
		//'drd' => [], // Earth Spirit - Pelt (57)
		//'ush' => [], // Troll Nest - Shie (57)
		//'uow' => [], // Aegis - Shie (59)
		//'ult' => [], // Hellforged Plate - Tors (59)
		//'uhm' => [], // Spired Helm - Helm (59)
		//'bae' => [], // Conquerer Crown - Phlm (60)
		//'utb' => [], // Mirrored Boots - Boot (60)
		//'nee' => [], // Succubae Skull - Head (60)
		//'uld' => [], // Kraken Shell - Tors (61)
		//'pae' => [], // Zakarum Shield - Ashd (61)
		//'uth' => [], // Lacquered Plate - Tors (62)
		//'dre' => [], // Sky Spirit - Pelt (62)
		//'utc' => [], // Troll Belt - Belt (62)
		//'rbe' => [], // Troll Belt [S] - Bels (62)
		'utp' => [ // Archon Plate - Tors (63)
			3 => 3,
			4 => 4,
			2 => 5,
			0 => 4,
		],
		//'uh9' => [], // Bone Visage - Helm (63)
		//'uts' => [], // Ward - Shie (63)
		//'ci3' => [], // Diadem - Circ (64)
		//'uhg' => [], // Ogre Gauntlets - Glov (64)
		//'uul' => [], // Shadow Plate - Tors (64)
		//'nef' => [], // Bloodlord Skull - Head (65)
		//'baf' => [], // Guardian Crown - Phlm (65)
		//'uhb' => [], // Myrmidon Greaves - Boot (65)
		//'urn' => [], // Corona - Helm (66)
		//'drf' => [], // Dream Spirit - Pelt (66)
		//'uar' => [], // Sacred Armor - Tors (66)
		//'paf' => [], // Vortex Shield - Ashd (66)
		//'uhc' => [], // Colossus Girdle - Belt (67)
	],

	// Set what tier to label these base weapon items.
	'weapons' => [
		//'axe' => [], // Axe - Axe (0)
		//'bal' => [], // Balanced Axe - Taxe (0)
		//'bkf' => [], // Balanced Knife - Tkni (0)
		//'bar' => [], // Bardiche - Pole (0)
		//'bsw' => [], // Bastard Sword - Swor (0)
		//'btx' => [], // Battle Axe - Axe (0)
		//'bst' => [], // Battle Staff - Staf (0)
		//'bld' => [], // Blade - Knif (0)
		//'btl' => [], // Blade Talons - H2h (0)
		//'bwn' => [], // Bone Wand - Wand (0)
		//'brn' => [], // Brandistock - Spea (0)
		//'bax' => [], // Broad Axe - Axe (0)
		//'bsd' => [], // Broad Sword - Swor (0)
		//'ces' => [], // Cestus - H2h (0)
		//'clw' => [], // Claws - H2h (0)
		//'clm' => [], // Claymore - Swor (0)
		//'clb' => [], // Club - Club (0)
		//'cbw' => [], // Composite Bow - Bow (0)
		//'mxb' => [], // Crossbow - Xbow (0)
		'crs' => [ // Crystal Sword - Swor (0)
			5 => 5,
			4 => 5,
			0 => 6,
		],
		//'dgr' => [], // Dagger - Knif (0)
		//'d33' => [], // Decoy Dagger - Knif (0)
		//'dir' => [], // Dirk - Knif (0)
		//'2ax' => [], // Double Axe - Axe (0)
		//'ob1' => [], // Eagle Orb - Orb (0)
		//'flc' => [], // Falchion - Swor (0)
		'fla' => [ // Flail - Mace (0)
			5 => 5,
			4 => 5,
			0 => 6,
		],
		//'flb' => [], // Flamberge - Swor (0)
		//'opl' => [], // Fulminating Potion - Tpot (0)
		//'gix' => [], // Giant Axe - Axe (0)
		//'gis' => [], // Giant Sword - Swor (0)
		//'g33' => [], // Gidbinn - Knif (0)
		//'glv' => [], // Glaive - Jave (0)
		//'cst' => [], // Gnarled Staff - Staf (0)
		//'gsc' => [], // Grand Scepter - Scep (0)
		//'gax' => [], // Great Axe - Axe (0)
		//'gma' => [], // Great Maul - Hamm (0)
		//'gsd' => [], // Great Sword - Swor (0)
		//'gwn' => [], // Grim Wand - Wand (0)
		//'hal' => [], // Halberd - Pole (0)
		//'hax' => [], // Hand Axe - Axe (0)
		//'axf' => [], // Hatchet Hands - H2h (0)
		//'hxb' => [], // Heavy Crossbow - Xbow (0)
		//'hfh' => [], // Hellforge Hammer - Hamm (0)
		//'hdm' => [], // Horadric Malus - Hamm (0)
		//'hst' => [], // Horadric Staff - Staf (0)
		//'hbw' => [], // Hunter's Bow - Bow (0)
		//'jav' => [], // Javelin - Jave (0)
		//'ktr' => [], // Katar - H2h (0)
		//'qf1' => [], // KhalimFlail - Mace (0)
		//'kri' => [], // Kriss - Knif (0)
		//'lax' => [], // Large Axe - Axe (0)
		//'lxb' => [], // Light Crossbow - Xbow (0)
		//'lbb' => [], // Long Battle Bow - Bow (0)
		//'lbw' => [], // Long Bow - Bow (0)
		//'lst' => [], // Long Staff - Staf (0)
		//'lsd' => [], // Long Sword - Swor (0)
		//'lwb' => [], // Long War Bow - Bow (0)
		//'mac' => [], // Mace - Mace (0)
		//'mau' => [], // Maul - Hamm (0)
		//'mpi' => [], // Military Pick - Axe (0)
		//'mst' => [], // Morning Star - Mace (0)
		//'pik' => [], // Pike - Spea (0)
		//'pil' => [], // Pilum - Jave (0)
		//'pax' => [], // Poleaxe - Pole (0)
		//'rxb' => [], // Repeating Crossbow - Xbow (0)
		//'sbr' => [], // Saber - Swor (0)
		//'ob2' => [], // Sacred Globe - Orb (0)
		//'scp' => [], // Scepter - Scep (0)
		//'scm' => [], // Scimitar - Swor (0)
		//'skr' => [], // Scissors Katar - H2h (0)
		'scy' => [ // Scythe - Sc9 (0)
			4 => 6,
			0 => 6,
		],
		//'sbb' => [], // Short Battle Bow - Bow (0)
		//'sbw' => [], // Short Bow - Bow (0)
		//'ssp' => [], // Short Spear - Jave (0)
		//'sst' => [], // Short Staff - Staf (0)
		//'ssd' => [], // Short Sword - Swor (0)
		//'swb' => [], // Short War Bow - Bow (0)
		//'spr' => [], // Spear - Spea (0)
		//'spt' => [], // Spetum - Spea (0)
		//'spc' => [], // Spiked Club - Club (0)
		//'msf' => [], // Staff Of The Kings - Staf (0)
		//'qf2' => [], // SuperKhalimFlail - Mace (0)
		//'tax' => [], // Throwing Axe - Taxe (0)
		//'tkf' => [], // Throwing Knife - Tkni (0)
		//'tsp' => [], // Throwing Spear - Jave (0)
		//'tpcs' => [], // TPot Cold Small - Tpot (0)
		//'tpfs' => [], // TPot Fire Small - Tpot (0)
		//'tri' => [], // Trident - Spea (0)
		//'2hs' => [], // Two-Handed Sword - Swor (0)
		//'vou' => [], // Voulge - Pole (0)
		//'wnd' => [], // Wand - Wand (0)
		//'wax' => [], // War Axe - Axe (0)
		//'whm' => [], // War Hammer - Hamm (0)
		//'wsp' => [], // War Scepter - Scep (0)
		//'wsc' => [], // War Scythe - Sc9 (0)
		//'wst' => [], // War Staff - Staf (0)
		//'wsd' => [], // War Sword - Swor (0)
		//'leg' => [], // Wirt's Leg - Club (0)
		//'wrb' => [], // Wrist Blade - H2h (0)
		//'ywn' => [], // Yew Wand - Wand (0)
		//'gpl' => [], // Strangling Gas Potion - Tpot (6)
		//'tpgs' => [], // TPot Gas Small - Tpot (6)
		//'tpls' => [], // TPot Light Small - Tpot (6)
		//'ob3' => [], // Smoked Sphere - Orb (8)
		//'opm' => [], // Exploding Potion - Tpot (12)
		//'tpcm' => [], // TPot Cold Medium - Tpot (12)
		//'tpfm' => [], // TPot Fire Medium - Tpot (12)
		//'ob4' => [], // Clasped Orb - Orb (13)
		//'am3' => [], // Maiden Spear - Aspe (14)
		//'am1' => [], // Stag Bow - Abow (14)
		//'gpm' => [], // Choking Gas Potion - Tpot (16)
		//'tpgm' => [], // TPot Gas Medium - Tpot (16)
		//'tplm' => [], // TPot Light Medium - Tpot (16)
		//'am5' => [], // Maiden Javelin - Ajav (17)
		//'9cl' => [], // Cudgel - Club (18)
		//'ob5' => [], // Dragon Stone - Orb (18)
		//'8sb' => [], // Edge Bow - Bow (18)
		//'9ss' => [], // Gladius - Swor (18)
		//'8ss' => [], // Jo Staff - Staf (18)
		//'9ja' => [], // War Javelin - Jave (18)
		//'9tk' => [], // Battle Dart - Tkni (19)
		//'9wn' => [], // Burnt Wand - Wand (19)
		//'9ha' => [], // Hatchet - Axe (19)
		//'9dg' => [], // Poignard - Knif (19)
		//'9sc' => [], // Rune Scepter - Scep (19)
		//'9sp' => [], // Barbed Club - Club (20)
		//'am4' => [], // Maiden Pike - Aspe (20)
		//'ops' => [], // Oil Potion - Tpot (20)
		//'am2' => [], // Reflex Bow - Abow (20)
		//'tpcl' => [], // TPot Cold Large - Tpot (20)
		//'tpfl' => [], // TPot Fire Large - Tpot (20)
		//'9b7' => [], // Lochaber Axe - Pole (21)
		//'9ar' => [], // Quhab - H2h (21)
		//'8hb' => [], // Razor Bow - Bow (21)
		//'9sr' => [], // War Spear - Spea (21)
		//'8lx' => [], // Arbalest - Xbow (22)
		//'9ax' => [], // Cleaver - Axe (22)
		//'9ta' => [], // Francisca - Taxe (22)
		//'9la' => [], // Military Axe - Axe (22)
		//'8lb' => [], // Cedar Bow - Bow (23)
		//'9ma' => [], // Flanged Mace - Mace (23)
		//'9pa' => [], // Partizan - Pole (23)
		//'8ls' => [], // Quarterstaff - Staf (23)
		//'9sb' => [], // Shamshir - Swor (23)
		//'9tr' => [], // Fuscina - Spea (24)
		//'ob6' => [], // Glowing Orb - Orb (24)
		//'gps' => [], // Rancid Gas Potion - Tpot (24)
		//'9di' => [], // Rondel - Knif (24)
		//'tpgl' => [], // TPot Gas Large - Tpot (24)
		//'tpll' => [], // TPot Light Large - Tpot (24)
		//'9wb' => [], // Wrist Spike - H2h (24)
		//'9gi' => [], // Ancient Axe - Axe (25)
		//'9wd' => [], // Ancient Sword - Swor (25)
		//'8hx' => [], // Balista - Xbow (25)
		//'9wh' => [], // Battle Hammer - Hamm (25)
		'9s8' => [ // Battle Scythe - Sc9 (25)
			4 => 5,
			5 => 5,
			0 => 5,
		],
		//'9bs' => [], // Battle Sword - Swor (25)
		//'9ba' => [], // Bearded Axe - Axe (25)
		//'9h9' => [], // Bec-de-Corbin - Pole (25)
		//'9vo' => [], // Bill - Pole (25)
		//'8cs' => [], // Cedar Staff - Staf (25)
		//'8rx' => [], // Chu-Ko-Nu - Xbow (25)
		//'9kr' => [], // Cinquedeas - Knif (25)
		//'9mp' => [], // Crowbill - Axe (25)
		//'9sm' => [], // Cutlass - Swor (25)
		//'9cm' => [], // Dacian Falx - Swor (25)
		//'9cr' => [], // Dimensional Blade - Swor (25)
		//'9ws' => [], // Divine Scepter - Scep (25)
		//'8cb' => [], // Double Bow - Bow (25)
		//'92h' => [], // Espadon - Swor (25)
		//'9gd' => [], // Executioner Sword - Swor (25)
		//'9ga' => [], // Gothic Axe - Axe (25)
		//'8lw' => [], // Gothic Bow - Bow (25)
		//'8bs' => [], // Gothic Staff - Staf (25)
		//'9b9' => [], // Gothic Sword - Swor (25)
		//'9gw' => [], // Grave Wand - Wand (25)
		//'9pi' => [], // Great Pilum - Jave (25)
		//'9wc' => [], // Grim Scythe - Sc9 (25)
		//'9ts' => [], // Harpoon - Jave (25)
		//'9qs' => [], // Holy Water Sprinkler - Scep (25)
		//'9b8' => [], // Hurlbat - Taxe (25)
		//'9mt' => [], // Jagged Star - Mace (25)
		//'9fl' => [], // Knout - Mace (25)
		//'9p9' => [], // Lance - Spea (25)
		//'8l8' => [], // Long Siege Bow - Bow (25)
		//'9gm' => [], // Martel De Fer - Hamm (25)
		//'9wa' => [], // Naga - Axe (25)
		//'9yw' => [], // Petrified Wand - Wand (25)
		//'8sw' => [], // Rune Bow - Bow (25)
		//'8ws' => [], // Rune Staff - Staf (25)
		//'9ls' => [], // Rune Sword - Swor (25)
		//'8s8' => [], // Short Siege Bow - Bow (25)
		//'8mx' => [], // Siege Crossbow - Xbow (25)
		//'9s9' => [], // Simbilan - Jave (25)
		//'9gl' => [], // Spiculum - Jave (25)
		//'9bl' => [], // Stilleto - Knif (25)
		//'9bt' => [], // Tabar - Axe (25)
		//'9bw' => [], // Tomb Wand - Wand (25)
		//'9fc' => [], // Tulwar - Swor (25)
		//'9gs' => [], // Tusk Sword - Swor (25)
		//'92a' => [], // Twin Axe - Axe (25)
		//'9m9' => [], // War Club - Hamm (25)
		//'9bk' => [], // War Dart - Tkni (25)
		//'9br' => [], // War Fork - Spea (25)
		//'9st' => [], // Yari - Spea (25)
		//'9fb' => [], // Zweihander - Swor (25)
		//'ama' => [], // Ceremonial Javelin - Ajav (26)
		//'ob7' => [], // Crystalline Globe - Orb (27)
		//'9xf' => [], // Fascia - H2h (27)
		//'am6' => [], // Ashwood Bow - Abow (29)
		//'ob8' => [], // Cloudy Sphere - Orb (30)
		//'9cs' => [], // Hand Scythe - H2h2 (30)
		//'am8' => [], // Ceremonial Spear - Aspe (32)
		//'9lw' => [], // Greater Claws - H2h2 (33)
		//'ob9' => [], // Sparkling Ball - Orb (34)
		//'am7' => [], // Ceremonial Bow - Abow (35)
		//'9tw' => [], // Greater Talons - H2h2 (37)
		//'oba' => [], // Swirling Crystal - Orb (37)
		//'am9' => [], // Ceremonial Pike - Aspe (38)
		//'amb' => [], // Matriarchal Bow - Abow (39)
		//'7cl' => [], // Truncheon - Club (39)
		//'7ja' => [], // Hyperion Javelin - Jave (40)
		//'9qr' => [], // Scissors Quhab - H2h2 (40)
		//'7ha' => [], // Tomahawk - Axe (40)
		//'7wn' => [], // Polished Wand - Wand (41)
		//'6sb' => [], // Spider Bow - Bow (41)
		//'7ss' => [], // Falcata - Swor (42)
		//'7la' => [], // Feral Axe - Axe (42)
		//'7ta' => [], // Flying Axe - Taxe (42)
		//'6lx' => [], // Pellet Bow - Xbow (42)
		//'7sp' => [], // Tyrant Club - Club (42)
		//'7dg' => [], // Bone Knife - Knif (43)
		//'7sr' => [], // Hyperion Spear - Spea (43)
		//'6ss' => [], // Walking Stick - Staf (43)
		//'obb' => [], // Heavenly Stone - Orb (44)
		//'72h' => [], // Legend Sword - Swor (44)
		//'7ar' => [], // Suwayyah - H2h2 (44)
		//'7sm' => [], // Ataghan - Swor (45)
		//'6hb' => [], // Blade Bow - Bow (45)
		//'amd' => [], // Matriarchal Spear - Aspe (45)
		//'7o7' => [], // Ogre Axe - Pole (45)
		//'7ax' => [], // Small Crescent - Axe (45)
		//'7sc' => [], // Mighty Scepter - Scep (46)
		//'7pi' => [], // Stygian Pilum - Jave (46)
		//'7wb' => [], // Wrist Sword - H2h2 (46)
		//'7sb' => [], // Elegant Blade - Swor (47)
		//'7ma' => [], // Reinforced Mace - Mace (47)
		//'6lb' => [], // Shadow Bow - Bow (47)
		//'7vo' => [], // Colossus Voulge - Pole (48)
		//'7tk' => [], // Flying Knife - Tkni (48)
		//'7yw' => [], // Ghost Wand - Wand (48)
		//'amf' => [], // MatriarchalJavelin - Ajav (48)
		//'7ba' => [], // Silver Edged Axe - Axe (48)
		//'7cm' => [], // Highland Blade - Swor (49)
		//'6ls' => [], // Stalagmite - Staf (49)
		//'7tr' => [], // Stygian Pike - Spea (49)
		//'obc' => [], // Eldritch Orb - Orb (50)
		//'6mx' => [], // Gorgon Crossbow - Xbow (50)
		//'6cb' => [], // Great Bow - Bow (51)
		//'7fc' => [], // Hydra Edge - Swor (51)
		//'7m7' => [], // Ogre Maul - Hamm (51)
		//'7xf' => [], // War Fist - H2h2 (51)
		//'7mt' => [], // Devil Star - Mace (52)
		//'72a' => [], // Ettin Axe - Axe (52)
		//'7di' => [], // Mithral Point - Knif (52)
		//'7gs' => [], // Balrog Blade - Swor (53)
		//'7s7' => [], // Balrog Spear - Jave (53)
		'7s8' => [ // Thresher - Sc9 (53)
			'ETH SOCK=5' => 3,
			'!ETH SOCK=5' => 4,
			'ETH SOCK=4' => 2,
			'!ETH SOCK=4' => 3,
			0 => 4,
		],
		//'7cs' => [], // Battle Cestus - H2h2 (54)
		//'7bt' => [], // Decapitator - Axe (54)
		//'6s7' => [], // Diamond Bow - Bow (54)
		'7cr' => [ // Phase Blade - Swor (54)
			6 => 4,
			5 => 2,
			4 => 6,
			3 => 5,
			0 => 2,
		],
		//'6cs' => [], // Elder Staff - Staf (55)
		//'7br' => [], // Mancatcher - Spea (55)
		//'6hx' => [], // Colossus Crossbow - Xbow (56)
		//'obd' => [], // Demon Heart - Orb (56)
		//'7bw' => [], // Lich Wand - Wand (56)
		//'7b7' => [], // Champion Sword - Swor (57)
		//'6l7' => [], // Crusader Bow - Bow (57)
		//'7fl' => [], // Scourge - Mace (57)
		//'7qs' => [], // Seraph Rod - Scep (57)
		//'7bk' => [], // Winged Knife - Tkni (57)
		//'7bs' => [], // Conquest Sword - Swor (58)
		//'7lw' => [], // Feral Claws - H2h2 (58)
		//'amc' => [], // Grand Matron Bow - Abow (58)
		'7pa' => [ // Cryptic Axe - Pole (59)
			'ETH SOCK=5' => 3,
			'!ETH SOCK=5' => 4,
			'ETH SOCK=4' => 2,
			'!ETH SOCK=4' => 3,
			0 => 4,
		],
		//'7gl' => [], // Ghost Glaive - Jave (59)
		//'7mp' => [], // War Spike - Axe (59)
		'7fb' => [ // Colossal Sword - Swor (60)
			'ETH SOCK=6' => 3,
			'ETH SOCK=5' => 3,
			'ETH SOCK=4' => 5,
			'ETH SOCK=0' => 5,
		],
		//'ame' => [], // Matriarchal Pike - Aspe (60)
		//'7tw' => [], // Runic Talons - H2h2 (60)
		//'6sw' => [], // Ward Bow - Bow (60)
		//'7b8' => [], // Winged Axe - Taxe (60)
		//'7ga' => [], // Champion Axe - Axe (61)
		//'7ls' => [], // Cryptic Sword - Swor (61)
		//'7wh' => [], // Legendary Mallet - Hamm (61)
		//'7kr' => [], // Fanged Knife - Knif (62)
		//'7st' => [], // Ghost Spear - Spea (62)
		//'6bs' => [], // Shillelah - Staf (62)
		'7gd' => [ // Colossus Blade - Swor (63)
			'ETH SOCK=6' => 3,
			'ETH SOCK=5' => 3,
			'ETH SOCK=4' => 5,
			'ETH SOCK=0' => 5,
		],
		//'6rx' => [], // Demon Crossbow - Xbow (63)
		'7h7' => [ // Great Poleaxe - Pole (63)
			'ETH SOCK=5' => 3,
			'!ETH SOCK=5' => 4,
			'ETH SOCK=4' => 2,
			'!ETH SOCK=4' => 3,
			0 => 4,
		],
		//'6lw' => [], // Hydra Bow - Bow (63)
		//'obe' => [], // Vortex Orb - Orb (63)
		'7wa' => [ // Berserker Axe - Axe (64)
			6 => 4,
			5 => 2,
			4 => 6,
			3 => 5,
			0 => 2,
		],
		//'7qr' => [], // Scissors Suwayyah - H2h2 (64)
		//'7gw' => [], // Unearthed Wand - Wand (64)
		//'7gm' => [], // Thunder Maul - Hamm (65)
		//'7ts' => [], // Winged Harpoon - Jave (65)
		//'6ws' => [], // Archon Staff - Staf (66)
		//'7ws' => [], // Caduceus - Scep (66)
		//'obf' => [], // Dimensional Shard - Orb (66)
		//'7wc' => [], // Giant Thresher - Sc9 (66)
		//'7gi' => [], // Glorious Axe - Axe (66)
		//'7bl' => [], // Legend Spike - Knif (66)
		//'7wd' => [], // Mythical Sword - Swor (66)
		//'7p7' => [], // War Pike - Spea (66)
	],

];
